---
- name: install utilities and dependencies
  package: name={{ item }} state=present
  become: yes
  with_items:
    - autoconf
    - automake
    - bison
    - bzip2
    - curl
    - gcc
    - gcc-c++
    - glibc-devel
    - libffi-devel
    - libtool
    - libyaml-devel
    - make
    - ntpdate
    - openssl-devel
    - pam-devel
    - patch
    - protobuf-devel
    - readline
    - readline-devel
    - vim
    - wget
    - zlib
    - zlib-devel

# Install mercurial and config
- name: Install versioning software
  package: name={{ item }} state=present
  become: yes
  with_items:
    - git
    - mercurial

- name: setup ntpdate cron
  cron: name="NTP Updater" minute="0" job="/usr/sbin/ntpdate -us clock.isc.org"
  become: yes
