---
- name: Copy server certificate files for ssl/tls
  copy: src=certs/{{ item }} dest=/home/vagrant/certs/{{ item }} mode=0644
  with_items:
    - ca.crt
    - README
    - server.crl
    - server.crt
    - server.key

- name: Create bucket types
  command: '{{ riak_admin }} bucket-type create {{ item.name }} ''{{ item.props }}'''
  with_items: it_bucket_types

- name: Activate bucket types
  command: '{{ riak_admin }} bucket-type activate {{ item.name }}'
  with_items: it_bucket_types

- name: Create user
  command: '{{ riak_admin }} security add-user {{ it_user.name }} password={{ it_user.password }}'

- name: Add source for user
  command: '{{ riak_admin }} security add-source {{ it_user.name }} 127.0.0.1/32 {{ it_user.password }}'

- name: Create cert user
  command: '{{ riak_admin }} security add-user {{ it_cert_user }}'

- name: Add source for user
  command: '{{ riak_admin }} security add-source {{ it_cert_user }} 127.0.0.1/32 certificate'

- name: Add grants
  command: '{{ riak_admin }} security grant riak_kv.get,riak_kv.put,riak_kv.delete,riak_kv.index,riak_kv.list_keys,riak_kv.list_buckets,riak_core.get_bucket,riak_core.set_bucket,riak_core.get_bucket_type,riak_core.set_bucket_type,search.admin,search.query on any to user'