---
- name: verify unzip is available
  tags: jenv.io
  yum: name=unzip state=present

- name: check jenv exists
  stat: path=~/.jenv/bin/jenv-init.sh
  register: jenv_init
  tags: jenv.io
  sudo: false

- name: Install jenv via script
  script: get.jenv.io.sh
  tags: jenv.io
  when: not dist.stat.exists
  sudo: false

- name: Install java
  command: jenv install java {{ java_version }}
  tags: jenv.io
  sudo: false

- name: Set default java candidate
  command: jenv default java {{ java_default }}
  tags: jenv.io
  sudo: false

- name: Set/verify java home in .bashrc
  lineinfile: dest=~/.bashrc regexp='^export JAVA_HOME' line='export JAVA_HOME=$HOME/.jenv/candidates/java/current/'
  tags: jenv.io
  sudo: false

- name: Install maven
  command: jenv install maven {{ java_maven_version }}
  tags: jenv.io
  when: java_maven_version
  sudo: false
